FROM adoptopenjdk:8-jre-hotspot
LABEL Description="Tomcat image to test tomcat-in-the-cloud. standalone tomcat version"
VOLUME /tmp
USER root
ENV OPENSHIFT_KUBE_PING_NAMESPACE="tomcat-in-the-cloud" \
    JAVA_OPTS=""
ADD target/dependency/tomcat.tar.gz apache-tomcat.tar.gz
